eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
microservice:
  payment-service:
    endpoints:
      endpoint:
       uri: http://PAYMENT-SERVICE/payment/makepayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/saveorder
